import { Playfair_Display } from "next/font/google";
import "./globals.css";

const robotMono = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Coffee Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotMono.className}>{children}</body>
    </html>
  );
}
